### ISSUE TITLE
Cannot find 'kaggle_sentiment.txt'

### ISSUE THREAD

**Issue by joelvinaykumar** [lucko515/sentiment-analysis#1]
Hi Luka,

Can you attach all the necessary files..

**Comment by lucko515** [comment]
Hi Joel,

Thank you for the question!

I didn't want to include the txt file because it was taken from the Kaggle, and there is a download link in the project's README. Anyhow, here is the link if you haven't seen it before: https://inclass.kaggle.com/c/si650winter11
